### ISSUE TITLE
transferPlayer is not working as expected

### ISSUE THREAD

**Issue by soepketel-dev** [Alemiz112/StarGate#4]
**Servers**
- WaterDog - StarGate installed.
- NukkitX - StarGate installed (lobby)
- NukkitX - StarGate installed (survival)

I created a simple (working) plugin which should transfer players from (example) lobby to survival.

Command: /ss [server]
Code:
`StarGateUniverse.getInstance().transferPlayer(player, server, client);`

When I execute **/ss survival** while in the survival server it gives the following error:

> You are already conneccted to this server!

When I execute **/ss survival** while in the lobby server nothing happens. No errors in consoles, nothing.

When I enter a non-existing server it says:

> Player was supposed to connect server that is unreachable!

**Comment by Alemiz112** [comment]
If this issue is still actual, please reopen it.
