### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by tunikakeks** [Alemiz112/StarGate#5]
Can you May add Portals dir Waterdog Transfers?

**Comment by Alemiz112** [comment]
I do not understand your idea. Can you describe it more?

**Comment by xxAROX** [comment]
I think, if you run thought nether portal be like

**Comment by tunikakeks** [comment]
> I do not understand your idea. Can you describe it more?

That you can also use portals to transfer on Waterdog Servers. Just search yesdog/Waterdog

**Comment by xxAROX** [comment]
That must be ServerSide>StarGate Atlantis/Universe

**Comment by xxAROX** [comment]
PocketMine:
```php
/**
 * @var \pocketmine\plugin\Plugin $this
 * @var \pocketmine\Player $player
 * @var string $server
 * @var alemiz\sga\client\Client $client
 */
$this->getScheduler()->scheduleRepeatingTask(new \pocketmine\scheduler\ClosureTask(int $currentTick): void{
     if ($player->getLevel()->getBlock($player->asVector3())->getId() == BlockIds::PORTAL) {
          \alemiz\sga\StarGateAtlantis::getInstance()->transferPlayer($player, $server, $client)
     }
}, 20 /2); //NOTE: half second.
```

**Comment by xxAROX** [comment]
create an issue [here](https://github.com/Alemiz112/StarGate-Atlantis) for more help lol.
