### ISSUE TITLE
[BUG] Unlimited Timer treads opened by StarGate cause server overload/crash

### ISSUE THREAD

**Issue by alkanex-xyz** [Alemiz112/StarGate#6]
**Describe the bug**
After setting up the Waterdog with StarGate parallel to our Bungee-network. We had a Out of Memory exception on our Java Servers: https://pastebin.com/r5RtVs6i

After some research we identified the waterdog screen as the cause for the crash, due to creating multiple threads and not stopping them. So we used "top -H" in console to watch the server threads: https://paste.pics/ee1d220db8d919288a61e9756c02270c
Every 30 seconds 3 new timer threads are started.
We disabled the StarGate plugin. the Waterdog runs smooth and doesn't create the threads. After reenabling the plugin and disabling one server. only 2 new threads every 30 seconds. Reenabling the third server: 3 new threads every 30 seconds.

We had a look into your sources and think that the serverping could cause this issue: https://github.com/Alemiz112/StarGate/blob/master/src/main/java/alemiz/stargate/gate/Server.java#L101

**Comment by mindw0rm** [comment]
The threads that hang are of class TimerThread, an internal class created by Timer. 
Maybe the issue can be resolved by not creating a new instance of Timer for each task, but reusing them?

**Comment by alkanex-xyz** [comment]
As the 1.16 is out now. Any updates regarding this problem?
The last thing you said:You wanted to build a version without timers. Maybe it's enough to build a version, which only create one timer instance per server an reuse it, instead of creating one every 30 seconds

**Comment by alkanex-xyz** [comment]
@Alemiz112 ?

**Comment by Alemiz112** [comment]
Sorry I was quite busy. I have tested it on more servers with custom OS. I can not reproduce your problem.

Actually timer instance is called and scheduled correctly. You can check official Java docs if you do not believe.

If I will find some time, I should be able to create custom version tomorrow.

**Comment by Alemiz112** [comment]
Closing as the issue was solved before and no new activity here.
