### ISSUE TITLE
[NO RECEIVE PACKET]

### ISSUE THREAD

**Issue by ImHammer** [Alemiz112/StarGate#8]
**Describe the bug**

NO RECEIVE PACKET...

Using waterdog and pocketmine downstream servers, the stargate server does not receive packets from stargate clients, not even the authentication packet.

**To Reproduce**
1. Create a waterdog proxy server
2. Create a pocketmine downstream server
3. install plugin StarGate server in waterdog and install plugin StarGate-Atlantis in pocketmine server
4. Turn on the waterdog first and then the pocketmine.
5. In your pocketmine (If it connects successfully) you receive this log "[StarGate-Atlantis] Client lobby has connected!"
6. But in your waterdog there will be no log.

**Result**
Try sending a serverInfo and you will see that there was no response from the stargate server.

**Additional context**
Thanks in advance.

**Comment by Alemiz112** [comment]
Hello,
Which build of Stargate Atlantis do you use?

Usually If the stagrate client version is compatible with stargate server, new client connected would be shown in server log too.

**Comment by ImHammer** [comment]
Sorry, I had made the mistake of using StarGate-Atlantis which is compatible with StarGate (WaterDogPE), since I was using the waterfall stargate, but now the stargate plugin (WaterDogPE) n initial, the waterdogpe n starts the plugin nor does it start the waterdogpe.

without stargate server for waterdogpe: It starts normally

~/foo/bar/Proxy $ ./start.sh
Starting WaterdogPE....
12:27:01 [INFO ] Starting WaterDogPE proxy software!
12:27:01 [INFO ] Software Version: 1.0.0
12:27:01 [INFO ] Build Version: #build
12:27:01 [INFO ] Development Build: true
12:27:01 [INFO ] Software Authors: WaterdogTEAM
12:27:01 [WARN ] Unknown build id. Custom build? Unofficial builds should be not run in production!
12:27:02 [DEBUG] Using fast codec! Please ensure plugin compatibility!
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=313, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=332, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=340, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=354, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=361, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=388, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=389, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=390, raknetVersion=9)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=407, raknetVersion=10)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=408, raknetVersion=10)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=419, raknetVersion=10)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=422, raknetVersion=10)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=428, raknetVersion=10)
12:27:03 [DEBUG] Registered custom BedrockCodec ProtocolVersion(protocol=431, raknetVersion=10)
12:27:03 [INFO ] Loading resource packs!
...


with stargate server: It shuts down unexpectedly and without any error.

~/foo/bar/Proxy $ ./start.sh
Starting WaterdogPE....
12:29:30 [INFO ] Starting WaterDogPE proxy software!
12:29:30 [INFO ] Software Version: 1.0.0
12:29:30 [INFO ] Build Version: #build
12:29:30 [INFO ] Development Build: true
12:29:30 [INFO ] Software Authors: WaterdogTEAM
12:29:30 [WARN ] Unknown build id. Custom build? Unofficial builds should be not run in production!
~/foo/bar/Proxy $

Would you help me ? I really need this plugin.

**Comment by Alemiz112** [comment]
In that case you are using incorrect stargate server plugin. Download stargate server plugin for WDPE [here](https://jenkins.waterdog.dev/job/StarGate/job/master/lastSuccessfulBuild/artifact/alemiz/stargate/stargate-waterdogpe/2.1-SNAPSHOT/stargate-waterdogpe-2.1-SNAPSHOT.jar).
